spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.200:3306/gulimall_ums?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  application:
    name: gulimall-member
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.200
    port: 6379
  session:
    # Spring Session 存储类型 : redis
    store-type: redis
  zipkin:
    base-url: http://192.168.56.200:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'
