spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.200
    port: 6379
  session:
    # Spring Session \u5B58\u50A8\u7C7B\u578B : redis
    store-type: redis

server:
  port: 12000
