server:
  port: 30000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.200
    port: 6379

# \u7EBF\u7A0B\u6C60 \u914D\u7F6E
gulimall:
  thread:
    # \u6838\u5FC3\u7EBF\u7A0B\u6570
    core-size: 20
    # \u6700\u5927\u7EBF\u7A0B\u6570
    max-size: 200
    # \u4F11\u7720\u65F6\u957F
    keep-alive-time: 10
