server:
  port: 40000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  redis:
    host: 192.168.56.200
    port: 6379
  zipkin:
    base-url: http://192.168.56.200:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

# 线程池 配置
gulimall:
  thread:
    # 核心线程数
    core-size: 20
    # 最大线程数
    max-size: 200
    # 休眠时长
    keep-alive-time: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
